### PR TITLE
Force regeneration

### PR DESCRIPTION
**Pull request by kelvinst**
So, hi...

I was passing through some problems when I am using the jekyll-compass plugins.

I was using it in [my blog](https://github.com/kelvinst/kelvinst.github.io), to use the compass sprites feature to make my blog rocks (it's in the start, but if you have some doubt from the rightness of the code, see my actual code at [here](https://github.com/kelvinst/kelvinst.github.io/tree/sprites)).

So, I'm almost sure that I make it all right (since it's very easy). Created the `_sass_` folder, and moved the .sass files to it. But, here comes the problem: each time that I `jekyll serve` my blog, **it toggles the css creation**. Once time creating the resulting css, and the other time removing it from the generated site.

Then, debuging and studying a little, I perceived that this is a jekyll's generators behavior. If I have something that was generated before, and is not generated now, then, this thing must be removed.

The compass command used, only generates the resulting css if the file changes ([here](https://github.com/chriseppstein/compass/blob/9ee6b422262668e8a7e154d2ac34f350ee331dc0/lib/compass/sass_extensions/sprites/sprite_methods.rb#L79) is the code that makes it). So, as you can see in the code, it was a `:force` option that you can pass to always regenerate.

It's what I've done!

Thanks...

### CODE REVIEW

**Comment by kelvinst** [comment]
Hope to see this shiped soon. Your plugin is very interesting and it has a lot of potential to grow with some time and more marketing (it was hard to find this, I only found because I tried to push a plugin with **exactly** the same name to RubyGems). :smiley: 

If you need help to make it better, I'm here.

**Comment by mscharley** [comment]
Hi Kelvin,

Thanks for the PR, I'll take a look at it later, but your correct, there's
currently no implementation of a watch feature during jekyll serve. If this
adds it, that would be great!

Thanks for the interest. Currently there's little to no promotion of the
plugin as it isn't configurable at all. That was going to be the first
thing I looked at.

Cheers,
Matt

**Comment by kelvinst** [comment]
Hi.

You're welcome. So, about the change: I did not add a watch feature, and even if I wanted to, I'll not be able to it. This must be done at jekyll core, since is the core that controls all the generation process and what must be placed and what must be removed from the generated site.

`jekyll serve` command have the `--watch` option, but this feature is in very "start edition". Each change in the site files, it regenerate all the site, and not just what is needed. So, a feature to regenerate in-demand is impossible to make on jekyll plugins because it doesn't have this feature itself.

What I've done was just align the plugin's behavior with jekyll's behavior, and always regenerate all. Maybe someday in the future, with a watch feature in jekyll, we can do it the best way.

Thanks.

**Comment by mscharley** [comment]
So, full rebuild every run. I purposely avoided it, and ideally this would be solved for both of us with #3. I purposely avoided it because Compass can take a little while to run when doing full rebuilds, especially when you are throwing spriting at it.

For now, I think I'll merge this because I do take your point about matching Jekyll's behaviour, but I think the best solution is allowing it to be configurable whether to force a full rebuild or not (via #3).

**Comment by mscharley** [comment]
I've also just pushed a 0.1.1 gem with these two commits merged.

**Comment by kelvinst** [comment]
Thanks õ/

**Comment by kelvinst** [comment]
And about your idea to avoid full rebuild, I'll try to think in a solution to it. :smiley: 

Thanks again for accepting the PRs

**Pull request merged**
