### PR TITLE
Changed jekyll runtime_dependency

### PR DESCRIPTION
**Pull request by fxruizx**
Updated the Jekyll being used from 2.0 to 3.0

### CODE REVIEW

**Comment by mscharley** [comment]
Seems reasonable, I'll look at this on the weekend when I have a bit more time. I want to do a bit of testing to make sure the plugin still works properly with Jekyll 3.0.

If you want to build and use the gem locally in the meantime you can run the following:

```
rake build
gem install jekyll-compass*.gem
```

**Comment by mscharley** [comment]
I'm having troubles getting jekyll-compass working with the latest versions of compass and jekyll 2.x so can't test the update to 3.x since I don't have a valid base-line. I haven't used Jekyll for over a year now and this project is more or less abandoned at the moment. If anyone else wants to debug, the message I keep getting is:

```
bundle exec jekyll build
Configuration file: /home/matt/Documents/Code/matt.scharley.me/_config.yml
            Source: ./src
       Destination: ./build
      Generating... 
Unable to find a valid configuration: sass_path=/home/matt/Documents/Code/matt.scharley.me/src/_compass
```

Not sure what's generating that error. Could be either Sass or Compass I suppose, but I tried pushing both of those all the way as low as possible and was still getting this issue.

**Comment by chikamichi** [comment]
@mscharley FYI I tested the latest build (1.3.0-pre) locally with Jekyll 2.5.3 & Compass 1.0.3, using different projects including a vanilla one (`jekyll new test-project`), and was not able to reproduce the aforementioned error.

I'm going to give Jekyll 3.0 a shot.

**Comment by mscharley** [comment]
Weird. To be honest, I haven't used jekyll in over a year so I'm not sure
what the current state of jekyll-compass looks like at all.

**Comment by chikamichi** [comment]
@mscharley I had no problem using latest build (1.3.0-pre) with Jekyll 3.0 on a vanilla project.

_Edit_: if you feel like releasing a new version with support for Jekyll 3.0, I'd suggest reworking the README which has many confusing or outdated parts. I could submit a PR :cat:

**Comment by mscharley** [comment]
PRs are definitely appreciated, or if you feel up to it I'm more than happy to transfer ownership of the gem on rubygems since I'm not really in a place to be able to keep this project updated

**Comment by chikamichi** [comment]
We could do that (the latter, transferring ownership to allow for new releases). I would gladly help :nail_care:

**Comment by mscharley** [comment]
I've listed you as an owner on the gem now :+1:

**Comment by chikamichi** [comment]
Nice, thank you!

**Comment by mscharley** [comment]
With that, I'm going to close this PR as 'won't fix'. Official repo for this project would now be https://github.com/chikamichi/jekyll-compass so probably best to reopen it there (or @chikamichi will probably just merge it in directly).

**Comment by chikamichi** [comment]
Will do, thx.

**Pull request closed without merging**
